# Wallpaper
preload = /home/domucchi/Downloads/wallhaven-gpl8d3.jpg
wallpaper = DP-4,/home/domucchi/Downloads/wallhaven-gpl8d3.jpg
wallpaper = DP-5,/home/domucchi/Downloads/wallhaven-gpl8d3.jpg
plash = true
