# Wallpaper
preload = /home/domucchi/pictures/wallpapers/frieren_wallpaper.jpg
wallpaper = DP-4,/home/domucchi/pictures/wallpapers/frieren_wallpaper.jpg
wallpaper = DP-5,/home/domucchi/pictures/wallpapers/frieren_wallpaper.jpg
plash = true
