# Plugins
# Catppuccin
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
run ~/.dotfiles/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Set default terminal mode
set -g default-terminal "screen-256color"

# Set prefix key to Ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Split window using
bind | split-window -h
bind - split-window -v

# Use neovim h,j,k,l to switch panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use Alt-arrow keys to switch between windows
bind -n M-right next-window
bind -n M-left previous-window
